--- 
# ansible playbook to bootstrap cloudshell on ubuntu 22.04
# the stage1 playbook runs with the root user and sets things up for the connor user later

- name: 'bootstrap cloudshell (stage 2)'
  hosts: cloudshell
  remote_user: connor
  vars_files:
    #- host_vars/cloudshell/vars.yml # placeholder
    - host_vars/cloudshell/secret.yml
    - host_vars/cloudshell/packages.yml

  tasks: # pre_tasks will run before the roles. important because roles depend on packages and hostname

  - name: Update packages
    become: true
    apt:
      update_cache: yes
      upgrade: full
      autoremove: true

  - name: install packages
    become: true
    package:
      name: "{{ install_packages }}"
      state: latest

  - name: "create $GOPATH directory"
    ansible.builtin.file:
      path: $HOME/.local/share/go
      state: directory
      mode: '0755'

  - name: check if zoxide exists
    stat: 
      path: $HOME/.local/bin/zoxide
    register: zoxide_status
  
  - name: Install Zoxide
    shell: curl -sS https://webinstall.dev/zoxide | bash
    when: zoxide_status.stat.exists == false

  - name: install tealdeer
    community.general.cargo:
      name: tealdeer

