--- # Configuration for my main VPS
- hosts: cloudshell
  vars_files:
    - /home/connor/code/ansible-playbooks/host_vars/cloudshell/secret.yml

  tasks:
    - import_tasks: tasks/debian/packages.yml
    - import_tasks: tasks/debian/system-config.yml
    - import_tasks: tasks/debian/neovim.yml
    - import_tasks: tasks/debian/password-store.yml
    - import_tasks: tasks/debian/syncthing.yml
    - import_tasks: tasks/debian/nginx.yml
    - import_tasks: tasks/debian/transcoding.yml
    - import_tasks: tasks/debian/sc-im.yml

  post_tasks:
    - name : remove duplicate tailscale gpg key left by artis3n.tailscale
      # NOTE: this is a hack to avoid fixing the error in artis3n.tailscale where it
      # creates a duplicate gpg key entry with the deprecated apt_key method
      become: yes
      file:
        path: /etc/apt/sources.list.d/pkgs_tailscale_com_stable_debian.list
        state: absent

  roles:
    - artis3n.tailscale
