---
- name: Configure homeworld server
  hosts: homeworld
  vars_files:
    - host_vars/homeworld/secret.yaml


  tasks:
    - name: Update apt cache
      become: true
      apt:
        update_cache: yes

    - name: Upgrade packages
      become: true
      apt:
        upgrade: safe
        autoremove: yes

    - name: Install packages
      become: true
      package:
        name: "{{ install_packages}}"
        state: present
