---
- name: Configure homeworld server
  hosts: homeworld
  vars_files:
    - host_vars/homeworld/secret.yaml


  tasks:
    - name: Update apt cache
      become: true
      apt:
        update_cache: yes

    - name: Upgrade packages
      become: true
      apt:
        upgrade: safe
        autoremove: yes

    - name: Install packages
      become: true
      package:
        name: "{{ install_packages}}"
        state: present

    - name: Check if just is installed
      stat:
        path: "/usr/local/bin/just"
      register: just_exists

    - name: Download just install script
      get_url:
        url: https://just.systems/install.sh
        dest: /tmp/install.sh
      when: just_exists.stat.exists == false

    - name: Make the script executable
      file:
        path: /tmp/install.sh
        mode: +x
      when: just_exists.stat.exists == false

    - name: Run just install script
      become: true
      command: /tmp/install.sh --to /usr/local/bin
      when: just_exists.stat.exists == false

    - name: Download lazydocker install script
      get_url:
        url: https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh
        dest: /tmp/install_lazydocker.sh

    - name: Make the script executable
      file:
        path: /tmp/install_lazydocker.sh
        mode: +x

    - name: Run lazydocker install script
      command: /tmp/install_lazydocker.sh

    - name: Install magic wormhole
      become: true
      get_url:
        url: https://github.com/magic-wormhole/magic-wormhole.rs/releases/download/0.6.0/wormhole-rs
        dest: /usr/local/bin/wormhole-rs
        mode: "a+x"

    - name: Check if SSH key exists
      stat:
        path: "~/.ssh/id_ed25519"
      register: ssh_key_exists

    - name: Generate SSH key if it doesn't exist
      command:
        cmd: ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -N ""
      when: ssh_key_exists.stat.exists == false

    - name: Read public key
      shell: cat ~/.ssh/id_ed25519.pub
      register: file_content
      when: ssh_key_exists.stat.exists == false

    - name: Print public key to terminal
      debug:
        msg: "{{ file_content.stdout }}"
      when: ssh_key_exists.stat.exists == false

    - name: 'Pause: add public key to GitHub'
      pause:
        prompt: "Press Enter to continue..."
      when: ssh_key_exists.stat.exists == false

    - name: Create ~/code folder
      file:
        path: ~/code
        state: directory

    - name: Check if ~/code/docker-compose exists
      stat:
        path: ~/code/docker-compose
      register: docker_compose_stat

    - name: Clone git repository
      git:
        repo: git@github.com:0xConnorRhodes/docker-compose.git
        dest: ~/code/docker-compose
        accept_hostkey: true
      when: docker_compose_stat.stat.exists == false

    - name: 'Create caddy_net Docker network'
      community.docker.docker_network:
        name: caddy_net
        state: present

    - name: 'Create proxmox user for web UI'
      become: true
      command: pveum useradd '{{ proxmox_user }}'@pve
      ignore_errors: true

    - name: Copy set-proxmox-pass script to server
      copy:
        src: configs/homeworld/set-proxmox-pass.sh
        dest: /tmp/set-proxmox-pass.sh
        mode: "a+x"

    - name: Execute script
      become: true
      command: /tmp/set-proxmox-pass.sh

    - name: Remove script
      file:
        path: /tmp/set-proxmox-pass.sh
        state: absent

    - name: 'set proxmox user permissions'
      become: true
      shell: |
        pveum aclmod / -user '{{ proxmox_user }}'@pve -role Administrator
        pveum aclmod / -user '{{ proxmox_user }}'@pve -role PVEAdmin
        pveum aclmod / -user '{{ proxmox_user }}'@pve -role PVEVMAdmin

    - name: 'copy nfs exports config'
      become: true
      copy:
        src: configs/homeworld/nfs-exports
        dest: /etc/exports
      notify:
        - Restart NFS service

  handlers:
    - name: Restart NFS service
      become: true
      service:
        name: nfs-kernel-server
        state: restarted
