--- # playbook for configuring dell latitude 5400 with Ubuntu
# first run: wget sfs.connorrhodes.com/bootstrap/ubuntu.sh && bash ubuntu.sh, then configure ssh access
- name: Configure personal laptop
  hosts: latitude
  vars_files:
    - host_vars/latitude/secrets.yml
    - host_vars/latitude/packages.yml


  tasks:
    - name: "Update apt cache"
      become: true
      apt:
        update_cache: true

    - name: "Upgrade packages"
      become: true
      apt:
        upgrade: safe
        autoremove: yes

    - name: "Install packages"
      become: true
      package:
        name: "{{ install_packages }}"
        state: present

    - name: 'Add the flathub flatpak repository remote to the user installation'
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user

    - name: "Install flatpak packages"
      community.general.flatpak:
        name: "{{ flatpak_packages }}"
        state: present
        method: user

  roles:
    - role: generate_ssh_key
    - role: PeterMosmans.customize-gnome
      vars:
        gnome_extensions:
          - id: 517 # caffeine
            enable: true
