--- # Configuration for my main VPS
- hosts: vmb
  vars_files:
    - /Users/c.rhodes/code/ansible-playbooks/host_vars/vmb/vars.yml
    - /Users/c.rhodes/code/ansible-playbooks/host_vars/vmb/secret.yml

  tasks:
    - import_tasks: tasks/macOS/mac-settings.yml
    - import_tasks: tasks/macOS/mac-packages.yml
    - import_tasks: tasks/macOS/make-directories.yml
