---
- hosts: ubuntu-testvm
  vars: 
    ansible_user: root
    ansible_password: "{{ lookup('community.general.passwordstore', 'sysadmin/temp-server-root') | password_hash('sha512') }}"
  tasks:
  - name: ping as root
    ansible.builtin.ping: