--- 
# ansible playbook to bootstrap silverstone home server from a default proxmox install

- name: 'bootstrap silverstone'
  hosts: silverstone
  remote_user: connor
  vars_files:
    - host_vars/silverstone/packages.yml
    - host_vars/silverstone/secret.yml

  pre_tasks: # pre_tasks will run before the roles. important because roles depend on packages and hostname

  - name: Update packages
    apt:
      update_cache: yes
      upgrade: full
      autoremove: true

  - name: create 'connor' user
    ansible.builtin.user:
      name: connor
      password: "{{ csh_user_password }}"
      shell: /bin/bash
      groups: sudo # add new groups like group1,group2,etc
      append: true

  - name: install packages
    package:
      name: "{{ install_packages }}"
      state: latest

  roles:
    - role: geerlingguy.docker
      vars:
        # these options ensure you can use `docker compose`
        docker_install_compose_plugin: true
        docker_compose_package: docker-compose-plugin
        docker_compose_package_state: present
        docker_users:
          - connor # handles adding connor to the docker group
        # note: must use `su - connor` or reboot to have access to docker without sudo

  post_tasks:

  - name: Reboot server
    ansible.builtin.command: reboot
    ignore_errors: true
