--- # Configure a host on my Tailnet
- name: Configure Tailnode
  hosts: tailnode
  vars_files:
    - host_vars/homeworld/secrets.yml


  tasks:
    - name: 'Update apt cache'
      become: true
      apt:
        update_cache: true

    - name: 'Upgrade packages'
      become: true
      apt:
        upgrade: safe
        autoremove: yes

    - name: 'Install apt packages'
      become: true
      apt:
        package:
          - curl
          - openssh-server
          - screen
          - fish
          - neovim

  roles:
    - role: create_user
      # user info specified in secrets.yml
    - role: artis3n.tailscale
      # tailscale auth key in secrets.yml
