---
- name: Configure homeworld server
  hosts: termux
  vars_files:
    - host_vars/phone/secrets.yml
    - host_vars/phone/packages.yml


  pre_tasks:
    - name: "check if storage has been setup"
      stat:
        path: ~/storage
      register: storage_directory

    - name: "termux-setup-storage: confirm on phone"
      shell: termux-setup-storage
      when: not storage_directory.stat.exists

    - name: "Install updates"
      command: "pkg upgrade -y"

    - name: "Install packages"
      command: "pkg add -y  {{ item }}"
      loop: "{{ install_packages }}"

    - name: Create secret directory
      file:
        path: "{{ ansible_env.HOME }}/.local/.secret"
        state: directory
        mode: '0755'

      # must copy through local script since the copy module does not work in termux
    - name: copy dotfiles encryption key
      local_action: 
        module: command
        argv:
          - /bin/bash
          - -c
          - /home/connor/code/ansible-playbooks/configs/termux/copy-key-to-host.sh

    # first run deploys chezmoi config but doesn't decrypt, second run decrypts encrypted files
    - name: 'init chezmoi dotfiles'
      command: chezmoi init --apply https://github.com/0xConnorRhodes/termux-dotfiles
      ignore_errors: true

    - name: 'init chezmoi dotfiles'
      command: chezmoi init --apply https://github.com/0xConnorRhodes/termux-dotfiles

    - name: 'configure ssh access to dotfiles repo 1'
      replace:
        path: "{{ ansible_env.HOME }}/.local/share/chezmoi/.git/config"
        regexp: 'https://github.com/0xConnorRhodes/termux-dotfiles'
        replace: 'git@github.com:0xConnorRhodes/termux-dotfiles.git'

    # ensures that, if the chezmoi init appends .git to the end of the https url, you don't wind up with 2 .git strings at the end of the ssh url
    - name: 'configure ssh access to dotfiles repo 2'
      replace:
        path: "{{ ansible_env.HOME }}/.local/share/chezmoi/.git/config"
        regexp: 'git@github.com:0xConnorRhodes/termux-dotfiles.git.git'
        replace: 'git@github.com:0xConnorRhodes/termux-dotfiles.git'
