--- # configure ubuntu test vm
- hosts: ubuntu-testvm

  tasks:
  - name: Add the user 'connor' with a bash shell, appending the group 'sudo'
    become: yes
    ansible.builtin.user:
      name: connor
      shell: /bin/bash
      groups: sudo
      append: yes

  - name: Upgrade the OS (apt full-upgrade)
    become: yes
    apt:
      update_cache: yes
      upgrade: full

  - name: Install Packages
    become: yes
    apt:
      pkg:
        - neovim
        - git
      state: latest
      cache_valid_time: 86400

  # configure git
  - name: test git config status
    ansible.builtin.shell: git config --list | grep user.name
    register: git_output
  - name: Configure git
    when: git_output.stdout != "user.name=Connor Rhodes"
    ansible.builtin.shell: |
      git config --global user.name "Connor Rhodes"
      git config --global user.email "cnnrrhodes@gmail.com"
      exit 0
  - name: copy git public to server
    ansible.builtin.copy:
      src: /home/ansible/.ssh/ansible-controlnode_ed25519
      dest: /home/ansible/.ssh/ansible-controlnode_ed25519
      owner: ansible
      group: ansible
      mode: '0600'
  - name: copy git private key to server
    ansible.builtin.copy:
      src: /home/ansible/.ssh/ansible-controlnode_ed25519.pub
      dest: /home/ansible/.ssh/ansible-controlnode_ed25519.pub
      owner: ansible
      group: ansible
      mode: '0644'
  - name: add github to ssh config
    # copy with only testination will create the file with the supplied content
    ansible.builtin.copy:
      dest: "/home/ansible/.ssh/config" 
      content: |
        Host github.com
            IdentityFile ~/.ssh/ansible-controlnode_ed25519
  - name: test if git configs are cloned
    ansible.builtin.shell: ls /configs 2>&1 | awk -F: '{ print $NF }'
    register: configsdir_status
    
  - name: prepare git configs folder
    become: yes
    ansible.builtin.file:
      path: /config
      state: directory
      group: connor
      owner: connor
      mode: '0755'

      
  - name: clone configs repo
    ansible.builtin.git:
      repo: git@github.com:connorhodes/my_dotfiles.git
      version: ubuntu-testvm
      dest: /configs