--- # configure ubuntu test vm
- hosts: ubuntu-testvm

  tasks:
  - name: Add the user 'connor' with a bash shell, appending the group 'sudo'
    become: yes
    ansible.builtin.user:
      name: connor
      shell: /bin/bash
      groups: sudo
      append: yes

  - name: Upgrade the OS (apt full-upgrade)
    become: yes
    apt:
      update_cache: yes
      upgrade: full

  - name: Install Packages
    become: yes
    apt:
      pkg:
        - neovim
        - git
        - unattended-upgrades
      state: latest
      cache_valid_time: 86400

  - name: enable unattended-upgrades
    ansible.builtin.systemd:
      name: unattended-upgrades
      state: started
      enabled: yes
      masked: no

  - name: add git user.name
    become: yes
    community.general.git_config:
      name: user.name
      scope: system
      value: "Connor Rhodes"
  - name: add git user.email
    become: yes
    community.general.git_config:
      name: user.email
      scope: system
      value: "cnnrrhodes@gmail.com"

  - name: copy git private key to ansible user
    ansible.builtin.copy:
      src: /home/ansible/.ssh/ansible-node-github-connorhodes
      dest: /home/ansible/.ssh/ansible-node-github-connorhodes
      owner: ansible
      group: ansible
      mode: '0600'
  - name: copy git public key to ansible user
    ansible.builtin.copy:
      src: /home/ansible/.ssh/ansible-node-github-connorhodes.pub
      dest: /home/ansible/.ssh/ansible-node-github-connorhodes.pub
      owner: ansible
      group: ansible
      mode: '0644'
  - name: copy git private key to server root user
    become: yes
    ansible.builtin.copy:
      src: /home/ansible/.ssh/ansible-node-github-connorhodes
      dest: /root/.ssh/ansible-node-github-connorhodes
      owner: root
      group: root
      mode: '0600'
  - name: copy git public key to server root user
    become: yes
    ansible.builtin.copy:
      src: /home/ansible/.ssh/ansible-node-github-connorhodes.pub
      dest: /root/.ssh/ansible-node-github-connorhodes.pub
      owner: root
      group: root
      mode: '0644'
  - name: copy git private key to server connor user
    become: yes
    ansible.builtin.copy:
      src: /home/ansible/.ssh/ansible-node-github-connorhodes
      dest: /home/connor/.ssh/ansible-node-github-connorhodes
      owner: connor
      group: connor
      mode: '0600'
  - name: copy git public key to server connor user
    become: yes
    ansible.builtin.copy:
      src: /home/ansible/.ssh/ansible-node-github-connorhodes.pub
      dest: /home/connor/.ssh/ansible-node-github-connorhodes.pub
      owner: connor
      group: connor
      mode: '0644'
  - name: add github to ansible ssh config
    # copy with only destination will create the file with the supplied content
    ansible.builtin.copy:
      dest: "/home/ansible/.ssh/config" 
      content: |
        Host github.com
            IdentityFile ~/.ssh/ansible-node-github-connorhodes
  - name: add github to connor ssh config 
    become: yes
    ansible.builtin.copy:
      dest: "/home/connor/.ssh/config" 
      content: |
        Host github.com
            IdentityFile ~/.ssh/ansible-node-github-connorhodes
      owner: connor
      group: connor
  - name: add github to root ssh config 
    become: yes
    ansible.builtin.copy:
      dest: "/root/.ssh/config" 
      content: |
        Host github.com
            IdentityFile ~/.ssh/ansible-node-github-connorhodes

  - name: test for root configs
    become: yes
    ansible.builtin.file: 
      path: /configs
      state: directory
    register: configstest
  
  - name: clone root configs
    become: yes
    ansible.builtin.shell: |
      set -o pipefail
      git clone --bare git@github.com:connorhodes/dotfiles-ubuntu-testvm.git --branch root --single-branch /configs
      # Alias
      shopt -s expand_aliases
      alias config='git --git-dir=/configs --work-tree=/'
      config config --local status.showUntrackedFiles no
      # Handle existing config
      mkdir -p /root/.root_default_configs_backup
      cd /configs
      config status | egrep "deleted:" | awk {'print $2'} | xargs -I{} mv {} /root/.root_default_configs_backup/
      # Install
      config checkout
    args: 
      chdir: "/"
      creates: "/.configs"
      executable: /bin/bash
    when: configstest.changed