# install sc-im from source

- name: install sc-im dependencies
  become: true
  apt:
    pkg:
      - gcc
      - bison
      - libncurses5-dev
      - libncursesw5-dev # wide character variant is best for sc-im
      - pkg-config
      - make
    update_cache: true

- name: clone sc-im from github
  ansible.builtin.git:
    repo: git clone https://github.com/andmarti1424/sc-im
    dest: /home/connor/.local/src/sc-im
    update: no
    single_branch: yes
    version: main
