# install sc-im from source

- name: install sc-im dependencies
  become: true
  apt:
    pkg:
      - gcc
      - bison
      - libncurses5-dev
      - libncursesw5-dev # wide character variant is best for sc-im
      - pkg-config
      - make
    update_cache: true

- name: clone sc-im from github
  ansible.builtin.git:
    repo: git@github.com:andmarti1424/sc-im.git
    dest: /home/connor/.local/src/sc-im
    update: no

# TODO: add automation for cd src/, make, sudo make install
