- name: Install ffmpeg for debian
  become: true
  package:
    name:
      - ffmpeg
      - libavformat-dev
      - libavfilter-dev
      - libavdevice-dev
    state: latest

- name: install pipx
  pip:
    name: pipx
    extra_args: --user

      #- name: Install auto-editor with pipx
      #  community.general.pipx:
      #    name: auto-editor
