---
- hosts: ubuntu-testvm
  gather_facts: yes
  tasks:

  - name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
    become: yes
    user:
      name: johnd
      comment: John Doe
      uid: 1010
      group: sudo

  # - name: Add the user 'janed' with a specific uid and a primary group of 'admin'
  #   become: yes
  #   user:
  #     name: janed
  #     comment: Jane Doe
  #     uid: 1030
  #     group: sudo

  # - name: Add custom new user
  #   become: yes
  #   user:
  #     name: "{{ new_user }}"
  #     comment: "{{ new_user }}"