--- # bootstrap cloudshell

# CONFIGURE MAIN VPS
- hosts: cloudshell
  gather_facts: yes
  tasks:

# CONFIGURE USERS AND LOGIN
  - name: Add the user 'connor' with a bash shell, appending the group 'sudo'
    become: yes
    ansible.builtin.user:
      name: connor
      password: "{{ lookup('community.general.passwordstore', 'sysadmin/main-vps-sudo-user') | password_hash('sha512') }}"
      shell: /bin/bash
      groups: sudo
      append: yes
  - name: Set hostname
    become: yes
    ansible.builtin.hostname:
      name: cs

# CLONE AND CHECKOUT CONFIGS
  - name: Install git (for config repo)
    become: yes
    apt:
      name:
        - git
      state: latest
      cache_valid_time: 86400
  - name: "ROLE: Clone and Checkout bare_git_repo_configs"
    include_role:
      name: bare_git_repo_configs
    vars:
      sudo_user: "connor" 
      configs_repo: "git@github.com:0xConnorRhodes/configs.cloudshell.git"
        
# INSTALL PACKAGES
  - name: Upgrade the OS (apt full-upgrade)
    become: yes
    apt:
      update_cache: yes
      upgrade: full
  - name: Install Packages # TODO: have ansible pull a package list from the git repo
    become: yes
    apt:
      name:
        - neovim
        - git
        - unattended-upgrades
        - fail2ban
        - htop
        - rsync
        - curl
        #- net-tools # provides route command
      state: latest
      cache_valid_time: 86400

# ENABLE SERVICES
  - name: enable unattended-upgrades
    ansible.builtin.systemd:
      name: unattended-upgrades
      state: started
      enabled: yes
      masked: no
  - name: enable fail2ban
    ansible.builtin.systemd:
      name: fail2ban
      state: started
      enabled: yes
      masked: no


## BOOTSTRAP NGINX  
#  - name: Install nginx Packages
#    become: yes
#    apt:
#      pkg:
#        - nginx
#        - python3-certbot-nginx
#      state: latest
#      cache_valid_time: 86400

# REBOOT IF REQUIRED # commented
  - name: "ROLE: reboot if required"
    include_role:
      name: debian_reboot_if_required
