# OS SETTINGS
- name: show full filepath in finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: _FXShowPosixPathInTitle 
    type: bool
    value: True
    # default = False
    state: present

- name: disable zoom animation when opening a new window of an existing application
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticWindowAnimationsEnabled
    type: bool
    value: False
    # default = True
    state: present

- name: disable desktop icons
  community.general.osx_defaults:
    domain: com.apple.finder
    key: CreateDesktop
    type: string
    value: false
    # default = true
    state: present

- name: disable press and hold function (enable repeat key on hold)
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: ApplePressAndHoldEnabled
    type: bool
    value: False
    # default = True
    state: present

- name: set delay before key repeat
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: InitialKeyRepeat
    type: int
    value: 10
    # default = 15
    state: present

- name: set key repeat rate
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: KeyRepeat
    type: int
    value: 1
    # default = 2
    state: present

- name: functionally disable dock
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide-delay
    type: float
    value: 1000
    # for 2 seconds until dock appears, et to 0.3
  register: dock_disable
 
- name: restart dock
  command: killall Dock
  when: dock_disable.changed

# APP SPECIFIC MODS
- name: disable iterm2 animations
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: HotkeyTermAnimationDuration
    type: float
    value: 0.00001
    state: present

- name: force Google Chrome into light mode
  community.general.osx_defaults:
    domain: com.google.Chrome
    key: NSRequiresAquaSystemAppearance
    type: bool
    value: True
    state: present

# CHANGE HOSTNAME AND COMPUTER NAME
# adapted from https://github.com/feffi/ansible-macos-computername

- name: set computer name
  become: true
  shell: 'scutil --set ComputerName "{{ Mac_ComputerName }}"'

- name: Set HostName
  become: true
  shell: 'scutil --set HostName "{{ Mac_HostName }}"'

- name: Set LocalHostName
  become: true
  shell: 'scutil --set LocalHostName "{{ Mac_LocalHostName }}"'

- name: Set NetBIOS name
  become: true
  community.general.osx_defaults:
    domain: "/Library/Preferences/SystemConfiguration/com.apple.smb.server"
    key: "NetBIOSName"
    type: "string"
    value: "{{ Mac_NetBIOSName | upper }}"
    state: present
