# PIPX
- name: Install pipx
  pip:
    name: pipx
    extra_args: --user

- name: Install sncli
  community.general.pipx:
    name: sncli

- name: Install unsilence
  community.general.pipx:
    name: unsilence

- name: Install brainfm
  community.general.pipx:
    name: brainfm

- name: Install organize
  community.general.pipx:
    name: organize-tool
